# Fast local development build for bpfman-operator
# Assumes binaries are already built with 'make build'
FROM quay.io/fedora/fedora-minimal

WORKDIR /

# Copy host-built operator binary
COPY ./bin/bpfman-operator .

# Copy required config files in one layer
COPY ./config ./config

USER 65532:65532

ENTRYPOINT ["/bpfman-operator"]