apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/instance: prometheus-metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: bpfman-operator
  name: bpfman-prometheus-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bpfman-metrics-reader
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
