apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/instance: agent-metrics-monitor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: agent-metrics-monitor
    app.kubernetes.io/part-of: bpfman-operator
  name: bpfman-agent-metrics-monitor
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /agent-metrics
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      insecureSkipVerify: false
      serverName: bpfman-agent-metrics-service.bpfman.svc
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: agent-metrics-service
      app.kubernetes.io/name: agent-metrics-service
