apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: agent-metrics-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/instance: agent-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: agent-metrics-service
    app.kubernetes.io/part-of: bpfman-operator
  name: bpfman-agent-metrics-service
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 8443
    protocol: TCP
    targetPort: https-metrics
  selector:
    name: bpfman-metrics-proxy
status:
  loadBalancer: {}
