apiVersion: v1
data:
  bpfman.agent.healthprobe.addr: :8175
  bpfman.agent.image: quay.io/bpfman/bpfman-agent:latest
  bpfman.agent.log.level: info
  bpfman.agent.metric.addr: :8443
  bpfman.image: quay.io/bpfman/bpfman:latest
  bpfman.log.level: info
  bpfman.toml: |
    [database]
    max_retries = 30
    millisec_delay = 10000
    [signing]
    allow_unsigned = true
    verify_enabled = true
kind: ConfigMap
metadata:
  annotations: {}
  labels: {}
  name: bpfman-config
