apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: bpfman-agent-role
rules:
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplicationstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplicationstates/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - bpfapplicationstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bpfman.io
  resources:
  - clusterbpfapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - clusterbpfapplications/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - clusterbpfapplicationstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfman.io
  resources:
  - clusterbpfapplicationstates/finalizers
  verbs:
  - update
- apiGroups:
  - bpfman.io
  resources:
  - clusterbpfapplicationstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
