apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-service
spec:
  ports:
    - name: https-metrics
      port: 8443
      protocol: TCP
      targetPort: https-metrics
  selector:
    control-plane: controller-manager
