apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
rules:
- apiGroups: [""]
  resources:
    - pods
    - services
    - endpoints
    - configmaps
    - secrets
  verbs:
    - get
    - list
    - watch
