apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-delegator
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: auth-delegator
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: bpfman-operator
  namespace: bpfman
- kind: ServiceAccount
  name: bpfman-daemon
  namespace: bpfman
