apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: bpfman-operator
    app.kubernetes.io/part-of: bpfman-operator
    app.kubernetes.io/managed-by: kustomize
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
