---
apiVersion: v1
kind: Namespace
metadata:
  name: acme
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-account
  namespace: acme
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-account
  namespace: acme
rules:
- apiGroups: ['', 'extensions', 'apps']
  resources: ['*']
  verbs: ['*']
- apiGroups: ['batch']
  resources:
  - jobs
  - cronjobs
  verbs: ['*']
- apiGroups:
    - bpfman.io
  resources:
    - bpfnsprograms
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - bpfman.io
  resources:
    - bpfnsprograms/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - bpfman.io
  # resources: ['xdpnsprograms']
  resources: ['bpfnsapplications', 'tcnsprograms', 'tcxnsprograms', 'uprobensprograms', 'xdpnsprograms']
  verbs:
    - create
    - delete
    - get
    - list
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-account
  namespace: acme
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-account
subjects:
  - kind: ServiceAccount
    name: test-account
    namespace: acme
---
apiVersion: v1
kind: Secret
metadata:
  name: test-account-token
  namespace: acme
  annotations:
    kubernetes.io/service-account.name: test-account
type: kubernetes.io/service-account-token
