apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-target-deployment
spec:
  selector:
    matchLabels:
      app: test-target
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test-target
    spec:
      containers:
        - name: test-target
          image: quay.io/bpfman-userspace/go-target:latest
          imagePullPolicy: IfNotPresent
