apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: bpfman-supervisor
        env:
        - name: KIND_HOST_PATH
          value: "/home/aim/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/aim/bin:/home/aim/.local/bin:/home/aim/.cargo/bin"
        volumeMounts:
        - name: home-aim
          mountPath: /home/aim
          readOnly: false
        - name: nix-store
          mountPath: /nix/store
          readOnly: true
        - name: run-user-1000
          mountPath: /run/user/1000
          readOnly: false
      volumes:
      - name: home-aim
        hostPath:
          path: /home/aim
          type: Directory
      - name: nix-store
        hostPath:
          path: /nix/store
          type: Directory
      - name: run-user-1000
        hostPath:
          path: /run/user/1000
          type: Directory
