[unix_http_server]
file=/run/supervisor/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor/supervisor.sock

[unix_http_server]
file=/run/supervisor/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
pidfile=/run/supervisord.pid

[program:env-helper]
command=/env-helper
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sshd]
command=/usr/sbin/sshd -D -E /proc/1/fd/1
autostart=true
autorestart=true

[program:bpfman]
command=/home/aim/src/github.com/bpfman/bpfman/target/debug/bpfman-rpc --timeout=0 --csi-support
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
