apiVersion: v1
items:
- apiVersion: bpfman.io/v1alpha1
  kind: BpfApplicationState
  metadata:
    creationTimestamp: "2025-03-04T22:12:48Z"
    finalizers:
    - bpfman.io.nsbpfapplicationcontroller/finalizer
    generation: 2
    labels:
      bpfman.io/ownedByProgram: bpfapplication-sample
      kubernetes.io/hostname: bpfman-deployment-control-plane
    name: bpfapplication-sample-39654e9e
    namespace: acme
    ownerReferences:
    - apiVersion: bpfman.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: BpfApplication
      name: bpfapplication-sample
      uid: ec225895-0954-4e6e-aa21-a32128e8bd73
    resourceVersion: "2232"
    uid: 66d14188-a467-4882-9207-214d82500e7b
  spec:
    appLoadStatus: LoadSuccess
    node: bpfman-deployment-control-plane
    programs:
    - name: tc_pass_test
      programId: 4125
      programLinkStatus: Success
      tc:
        links:
        - containerPid: 3078
          direction: Ingress
          interfaceName: eth0
          linkId: 832290746
          linkStatus: Attached
          priority: 55
          proceedOn:
          - pipe
          - dispatcher_return
          shouldAttach: true
          uuid: 00168ad2-abcd-427c-96b8-7ec2b73b8460
        - containerPid: 2981
          direction: Ingress
          interfaceName: eth0
          linkId: 256466427
          linkStatus: Attached
          priority: 55
          proceedOn:
          - pipe
          - dispatcher_return
          shouldAttach: true
          uuid: 3d99959a-6690-4de9-a8b5-26ade29525d2
      type: TC
    - name: tcx_next_test
      programId: 4126
      programLinkStatus: Success
      tcx:
        links:
        - containerPid: 3078
          direction: Egress
          interfaceName: eth0
          linkId: 533548322
          linkStatus: Attached
          priority: 100
          shouldAttach: true
          uuid: b299efd7-b0af-4ba7-8ed7-dfe067d80de2
        - containerPid: 2981
          direction: Egress
          interfaceName: eth0
          linkId: 777895864
          linkStatus: Attached
          priority: 100
          shouldAttach: true
          uuid: 5918b228-4724-43dc-8462-28d69a5cdcde
      type: TCX
    - name: uprobe_test
      programId: 4127
      programLinkStatus: Success
      type: UProbe
      uprobe:
        links:
        - containerPid: 3078
          function: malloc
          linkId: 1103062122
          linkStatus: Attached
          offset: 0
          shouldAttach: true
          target: libc
          uuid: b76f7b7b-7e24-4ad3-858e-ef6dc9abc561
    - name: uretprobe_test
      programId: 4128
      programLinkStatus: Success
      type: URetProbe
      uretprobe:
        links:
        - containerPid: 3078
          function: malloc
          linkId: 2890973738
          linkStatus: Attached
          offset: 0
          shouldAttach: true
          target: libc
          uuid: 25495af0-988e-4ca5-9d5a-3c2380f2b490
    - name: xdp_pass_test
      programId: 4129
      programLinkStatus: Success
      type: XDP
      xdp:
        links:
        - containerPid: 3078
          interfaceName: eth0
          linkId: 1368615850
          linkStatus: Attached
          priority: 100
          proceedOn:
          - pass
          - dispatcher_return
          shouldAttach: true
          uuid: 6f8ad067-99c7-4ba3-a61d-a4f3f4fc56b9
        - containerPid: 2981
          interfaceName: eth0
          linkId: 3080543731
          linkStatus: Attached
          priority: 100
          proceedOn:
          - pass
          - dispatcher_return
          shouldAttach: true
          uuid: 19c62c5c-c544-41fe-ab80-e9a6fc3e4fce
    updateCount: 2
  status:
    conditions:
    - lastTransitionTime: "2025-03-04T22:12:50Z"
      message: The BPF application has been successfully loaded and attached
      reason: Success
      status: "True"
      type: Success
kind: List
metadata:
  resourceVersion: ""
