apiVersion: bpfman.io/v1alpha1
kind: UprobeNsProgram
metadata:
  labels:
    app.kubernetes.io/name: uprobensprogram
  name: uprobe-example
  namespace: acme
spec:
  # Select all nodes
  nodeselector: {}
  bpffunctionname: my_uprobe
  func_name: syscall
  # offset: 0 # optional offset w/in function
  target: libc
  retprobe: false
  # pid: 0 # optional pid to execute uprobe for
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/uprobe:latest
  globaldata:
    GLOBAL_u8:
      - 0x01
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
  containers:
    pods:
      matchLabels:
        app: nginx
    containernames:
      - nginx
