apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: clusterbpfapplication
  name: clusterbpfapplication-sample
spec:
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/app-test:latest
  globalData:
    GLOBAL_u8:
      - 0x01
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
  programs:
    - name: kprobe_test
      type: KProbe
      kprobe:
        links:
          - function: try_to_wake_up
            offset: 0
    - name: kretprobe_test
      type: KRetProbe
      kretprobe:
        links:
          - function: try_to_wake_up
    - name: tracepoint_test
      type: TracePoint
      tracepoint:
        links:
          - name: syscalls/sys_enter_openat
    - name: tc_pass_test
      type: TC
      tc:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 55
            direction: Ingress
          - interfaceSelector:
              interfaces:
                - eth0
            priority: 100
            direction: Egress
            networkNamespaces:
              namespace: bpfman
              pods:
                matchLabels:
                  name: bpfman-daemon
    - name: tcx_next_test
      type: TCX
      tcx:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 500
            direction: Ingress
          - interfaceSelector:
              interfaces:
                - eth0
            priority: 100
            direction: Egress
            networkNamespaces:
              namespace: bpfman
              pods:
                matchLabels:
                  name: bpfman-daemon
    - name: uprobe_test
      type: UProbe
      uprobe:
        links:
          - function: malloc
            target: libc
            containers:
              namespace: bpfman
              pods:
                matchLabels:
                  name: bpfman-daemon
              containerNames:
                - bpfman
                - bpfman-agent
    - name: uretprobe_test
      type: URetProbe
      uretprobe:
        links:
          - function: malloc
            target: libc
            containers:
              namespace: bpfman
              pods:
                matchLabels:
                  name: bpfman-daemon
              containerNames:
                - bpfman
                - bpfman-agent
    - name: xdp_pass_test
      type: XDP
      xdp:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 55
          - interfaceSelector:
              interfaces:
                - eth0
            priority: 100
            networkNamespaces:
              namespace: bpfman
              pods:
                matchLabels:
                  name: bpfman-daemon
    - name: fentry_test
      type: FEntry
      fentry:
        function: do_unlinkat
        links:
          - mode: "Attach"
    - name: fexit_test
      type: FExit
      fexit:
        function: do_unlinkat
        links:
          - mode: "Attach"
