apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: clusterbpfapplication
  name: clusterbpfapplication-sample-if-dicovery
spec:
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/app-test:latest
  globalData:
    GLOBAL_u8:
      - 0x01
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
  programs:
    - name: tc_pass_test
      type: TC
      tc:
        links:
          - interfaceSelector:
              interfacesDiscoveryConfig:
                interfaceAutoDiscovery: true
                allowedInterfaces:
                  - "/veth*/"
            direction: Ingress
    - name: tcx_next_test
      type: TCX
      tcx:
        links:
          - interfaceSelector:
              interfacesDiscoveryConfig:
                interfaceAutoDiscovery: true
            direction: Ingress
          - interfaceSelector:
              interfacesDiscoveryConfig:
                interfaceAutoDiscovery: true
            direction: Egress
    - name: xdp_pass_test
      type: XDP
      xdp:
        links:
          - interfaceSelector:
              interfacesDiscoveryConfig:
                interfaceAutoDiscovery: true
