apiVersion: bpfman.io/v1alpha1
kind: TcxProgram
metadata:
  labels:
    app.kubernetes.io/name: tcxprogram
  name: tcx-containers
spec:
  bpffunctionname: tcx_next
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    interfaces:
      - eth0
  priority: 0
  direction: ingress
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/tcx_test:latest
  globaldata:
    GLOBAL_u8:
      - 0x01
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
  containers:
    namespace: bpfman
    pods:
      matchLabels:
        name: bpfman-daemon
    containernames:
      - bpfman
      - bpfman-agent
