apiVersion: bpfman.io/v1alpha1
kind: BpfNsApplication
metadata:
  labels:
    app.kubernetes.io/name: bpfnsapplication
  name: bpfapplication-sample
  namespace: acme
spec:
  # Select all nodes
  nodeselector: {}
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/go-app-counter:latest
  programs:
    - type: TC
      tc:
        bpffunctionname: stats
        interfaceselector:
          primarynodeinterface: true
        priority: 55
        direction: ingress
        containers:
          pods:
            matchLabels:
              app: nginx
    - type: TCX
      tcx:
        bpffunctionname: tcx_stats
        interfaceselector:
          primarynodeinterface: true
        priority: 500
        direction: ingress
        containers:
          pods:
            matchLabels:
              app: nginx
    - type: Uprobe
      uprobe:
        bpffunctionname: uprobe_counter
        func_name: malloc
        target: libc
        retprobe: false
        containers:
          pods:
            matchLabels:
              app: nginx
    - type: XDP
      xdp:
        bpffunctionname: xdp_stats
        interfaceselector:
          primarynodeinterface: true
        priority: 55
        containers:
          pods:
            matchLabels:
              app: nginx
