# To use this sample, you need to deploy the test-target application using the
# following command:
# kubectl apply -f hack/test-deployment.yaml
apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: clusterbpfapplication
  name: clusterbpfapplication-sample-netns
spec:
  nodeSelector: {}
  byteCode:
    image:
      url: quay.io/bpfman-bytecode/app-test:latest
  programs:
    - name: tc_pass_test
      type: TC
      tc:
        links:
          - interfaceSelector:
              interfaces:
                - eth0
            priority: 100
            direction: Egress
            networkNamespaces:
              pods:
                matchLabels:
                  app: test-target
    - name: tcx_next_test
      type: TCX
      tcx:
        links:
          - interfaceSelector:
              interfaces:
                - eth0
            priority: 100
            direction: Egress
            networkNamespaces:
              pods:
                matchLabels:
                  app: test-target
    - name: xdp_pass_test
      type: XDP
      xdp:
        links:
          - interfaceSelector:
              interfaces:
                - eth0
            priority: 100
            networkNamespaces:
              pods:
                matchLabels:
                  app: test-target
