apiVersion: bpfman.io/v1alpha1
kind: TcxNsProgram
metadata:
  labels:
    app.kubernetes.io/name: tcxnsprogram
  name: tcx-containers
  namespace: acme
spec:
  bpffunctionname: tcx_next
  # Select all nodes
  nodeselector: {}
  interfaceselector:
    interfaces:
      - eth0
  priority: 0
  direction: ingress
  bytecode:
    image:
      url: quay.io/bpfman-bytecode/tcx_test:latest
  globaldata:
    GLOBAL_u8:
      - 0x01
    GLOBAL_u32:
      - 0x0D
      - 0x0C
      - 0x0B
      - 0x0A
  containers:
    pods:
      matchLabels:
        app: nginx
    containernames:
      - nginx
