# This patch configures the operator deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: controller-manager-metrics-tls
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: bpfman-operator
          args:
            - --health-probe-bind-address=:8175
            - --metrics-bind-address=:8443
            - --leader-elect
            - --cert-dir=/tmp/k8s-webhook-server/serving-certs
          ports:
            - containerPort: 8443
              protocol: TCP
              name: https-metrics
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: controller-manager-metrics-tls
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
      volumes:
        - name: controller-manager-metrics-tls
          secret:
            secretName: controller-manager-metrics-tls
