apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bpfman-agent-role
  namespace: bpfman
rules:
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list", "watch"]
