apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bpfman-agent-rolebinding
  namespace: bpfman
subjects:
- kind: ServiceAccount
  name: bpfman-daemon
  namespace: bpfman
roleRef:
  kind: Role
  name: bpfman-agent-role
  apiGroup: rbac.authorization.k8s.io
